### ISSUE TITLE
moleculer-elasticsearch invalid apiVersion

### ISSUE THREAD

**Issue by benjick** [moleculerjs/moleculer-addons#47]
Getting the following error running `moleculer-elasticsearch`:

```
Invalid apiVersion "5.4", expected a function or one of 7.0, _default, 6.7, 6.6, 6.5, 6.4, 6.3, 6.2, 6.1, 6.0, 5.6, 2.4, 1.7, 0.90, 6.8, 7.1, 7.x, master
```

My service looks like this:

```
name: 'storyblok',
  mixins: [ESService],
  settings: {
    elasticsearch: {
      host: env.STORYBLOK_ELASTICSEARCH,
    },
  },
}
```

docker-compose:
```
version: '3.4'
services:
  elasticsearch:
    image: elasticsearch:5.5.0
```
